"use client";

// // self polyfill
// if (typeof self === "undefined") {
//   self = globalThis as unknown as Window;
// }

import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "../GlobalRedux/provider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full select-none h-full bg-white">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
