"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navlink from "./components/navlink";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <div className="w-full h-full">
        <div className="flex h-screen w-full gap-[50px] px-[20px] py-[50px]">
          <div className="w-[100px] h-full rounded-[10px] bg-white flex flex-col">
            <div className="w-full rounded-full bg-[whitesmoke] aspect-square justify-center items-center flex font-[700] text-[35px] text-center">
              <span className="text-[#1d4e4b]">C</span>
              <span className="text-[#fc6719]">B</span>
            </div>
            <div className=" w-full h-max  flex flex-col p-[10px]">
              <Navlink href="/dashboard">
                <div className="flex flex-col justify-center items-center gap-[10px] w-full aspect-square">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="1.5"
                    stroke="currentColor"
                    className="w-4"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M8.25 6.75h12M8.25 12h12m-12 5.25h12M3.75 6.75h.007v.008H3.75V6.75zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zM3.75 12h.007v.008H3.75V12zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm-.375 5.25h.007v.008H3.75v-.008zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z"
                    />
                  </svg>
                  <span className="text-[12px]">Post lists</span>
                </div>
              </Navlink>
              <Navlink href="/dashboard/create">
                <div className="flex flex-col justify-center items-center gap-[10px] w-full aspect-square">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="1.5"
                    stroke="currentColor"
                    className="w-4"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125"
                    />
                  </svg>
                  <span className="text-[12px]">New post</span>
                </div>
              </Navlink>
            </div>
          </div>
          <div className="bg-[whitesmoke] rounded-[30px] flex-1 p-[50px] scrollbar-hide overflow-y-auto">
            {children}
          </div>
        </div>
      </div>
    </main>
  );
}
